//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachKCV
    {
        public int STT { get; set; }
        public string KCV_Type { get; set; }
        public string KCV { get; set; }
        public string KCV_Name { get; set; }
        public string SIZE { get; set; }
        public string Thong_So_KCV { get; set; }
        public Nullable<decimal> MEASURE { get; set; }
        public string MEASURE_Details { get; set; }
        public Nullable<decimal> TLSP { get; set; }
        public Nullable<int> SL { get; set; }
        public string Retail_Price { get; set; }
        public string Discount { get; set; }
        public string POS_Discount { get; set; }
        public string Note { get; set; }
    }
}
