//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POS_Entities : DbContext
    {
        public POS_Entities()
            : base("name=POS_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<PhieuQuaTang> PhieuQuaTangs { get; set; }
        public DbSet<DanhSachKCV> DanhSachKCVs { get; set; }
    }
}
